import pygame

BODY_WIDTH = 20
BODY_HEIGHT = 20
PLAYABLE_WIDTH = 380
PLAYABLE_HEIGHT = 380
SCREEN_WIDTH = 380
SCREEN_HEIGHT = 450
APPLE_EVENT = pygame.USEREVENT + 1
GROW_EVENT = pygame.USEREVENT + 2
MAX_SNAKE = 289
